name: Release

on:
  push:
    tags:
      - v**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-artifacts:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: mkdir results
      - name: Build source
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czvf results/tasks-$GITHUB_REF_NAME.tar.gz -C $(nix eval --raw .#plugin.src.outPath) . --transform="s/^\\./tasks-$GITHUB_REF_NAME/"
      - name: Build wrapper
        run: |
          nix bundle .#wrapper --bundler github:NixOS/bundlers#toAppImage -o results/nvim-with-tasks-$GITHUB_REF_NAME-$(nix eval --impure --raw --expr builtins.currentSystem).AppImage

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: results/*
  create-release:
    runs-on: ubuntu-slim
    needs: build-artifacts
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: artifact-*
          path: artifacts
          merge-multiple: true
      - name: Create release
        run: |
          gh release create $GITHUB_REF_NAME artifacts/**
        env:
          GH_TOKEN: ${{ github.token }}
